### ISSUE TITLE
Implement parsing

### ISSUE THREAD

**Issue by f3ath** [f3ath/json-api-document-dart#8]
Look at the tests to get the idea of parsing API https://github.com/f3ath/json-api-dart/blob/master/test/meta_document_test.dart

**Comment by Schillen** [comment]
Hello, I would like to use your parser. Are you still planning to implement it? Greetings

**Comment by f3ath** [comment]
Hi! Yes, absolutely. Can you tell me about your use case? This way I can prioritize the most important parts.

**Comment by f3ath** [comment]
@Schillen Hey Marcel, I just released a new version which includes parsing. Would you mind giving it a try?

**Comment by Schillen** [comment]
Thank you for the fast reply.

my json structure looks like this. 
{"data": [{
...."attributes":{"key":"value"},
...."key":"value",
...."category":{
........"category":{
............"key":"value"

I´ll give it a try and let you know how it turned out.

**Comment by f3ath** [comment]
Hey @Schillen were you able to try it out?
